### PR TITLE
deb python-yaml only contains modules for Python 2

### PR DESCRIPTION
**Pull request by bwildenhain**
findfree is needs python3, so python3-yaml has to be installed on
Debian to use it

### CODE REVIEW

**Comment by mweinelt** [comment]
And we only need the one for python3, no reason to install the one for python2 as well. Please update your pull request accordingly, thanks!

**Comment by bwildenhain** [comment]
In this case, I would like to change the scripts which specify "#!/usr/bin/env python"  as interpreter to use python3, too.

Should I also add the dependencies not yet mentioned (mkbgp and apireader.py needs python3-requests, mkwikitable needs python3-jinja2) or would you prefer that in a separate commit?

**Comment by mweinelt** [comment]
Agreed, make them use 
```
#!/usr/bin/env python3.tx
```
instead.

Make a separate commit to fix the dependencies, would be best if it was a `requirements.txt` file from `pip freeze`.

**Comment by bwildenhain** [comment]
Ok, just changed the files and created requirements.txt.

**Comment by jplitza** [comment]
As there were more commits than necessary in this PR (namely a merge commit and the original commit that was completely overridden by a later one), I cherry-picked the last two commits (and fixed the only instance where the switch to Python 3 needed adjustments).

**Pull request closed without merging**
