### PR TITLE
Network processing

### PR DESCRIPTION
**Pull request by sargon**
Some scripts working with the networks part of the metadata.

### CODE REVIEW

**Comment by mweinelt** [comment]
I can only guess what you want to use this for. Probably allow-* blocks in bind, but the use case seems rather narrow and the description is vague at best.

**Comment by sargon** [comment]
The use case is quite simple. Instead of allowing various large networks, e.g. fc00::/7, we want explicitly allow access of networks of other communities to our zones. Since some of them started to use public ipv6 address spaces in their networks. So its for security reasons.

Another target would be the creation of firewall rules, to be able to filter on the forwarding chain.

**Comment by mweinelt** [comment]
But this is not exclusively a BindFormatter then. Why not refactor this to allow any seperator, because the schema is usually the same: network, seperator, newline

**Comment by sargon** [comment]
Yes, you are right, therefore I have reapplied the pattern used in the other scripts, so it is expendable for other formatters. 

Maybe, but thats not a task for this pr, we should redesign the whole script-set, so that the script all use the same set of formatters, but in different ways, e.g. use other formatters methods. It looks like this was planned from the beginning.

**Pull request closed without merging**
